[package]
name = "clouddns-nat-helper"
version = "0.2.6"
edition = "2021"
description = "Autogenerate A records for NAT setups from AAAA records in cloud providers"
license-file = "LICENSE"
repository = "https://github.com/maxhoesel/clouddns-nat-helper"
keywords = ["dns", "cloud", "cloudflare", "nat", "ipv4"]
categories = ["command-line-utilities"]
exclude = [
    ".github",
    "imgs",
    ".dockerignore",
    "Dockerfile",
    "helm",
    ".gitignore",
    ".pre-commit-config.yaml",
    "lcov.info",
    "Makefile.toml",
]

[dev-dependencies]
mockall = "0.11.3"
serde_json = "1.0.87"
chrono = "0.4.22"
totems = "0.2.7"

[dependencies]
clap = { version = "4.0.14", features = ["derive", "env"] }
cloudflare = { version = "0.9.1", features = ["rustls-tls"], default-features = false}
dnsclient = "0.1.17"
domain = { version = "0.7.0" }
env_logger = "0.9.1"
http = "0.2.8"
itertools = "0.10.5"
log = "0.4.17"
mockall_double = "0.3.0"
tokio = { version = "1.21.2", features = ["time", "macros"] }

[patch.crates-io]
cloudflare = { git = "https://github.com/maxhoesel/cloudflare-rs" }
