[package]
name = "cloddns-nat-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = "0.7.0"
http = "0.2.8"
serde = "1.0.145"

[dependencies.cloudflare]
path = "vendor/cloudflare-rs"
