[package]
name = "cloddns-nat-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
cloudflare = "0.9.1"
dnsclient = "0.1.17"
domain = { version = "0.7.0" }
http = "0.2.8"
itertools = "0.10.5"
log = "0.4.17"
serde = "1.0.145"
serde_json = "1.0.85"

[patch.crates-io]
cloudflare = { git = "https://github.com/maxhoesel/cloudflare-rs" }
