[tasks.install-clippy]
private = true
install_crate = { rustup_component_name = "clippy", binary = "clippy", test_arg = "--help" }

[tasks.install-rustfmt]
private = true
install_crate = { rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help" }

[tasks.install-cross]
private = true
install_crate = { crate_name = "cross", binary = "cross", test_arg = "--help" }


[tasks.install-pre-commit-hook]
private = true
script = '''
#!/usr/bin/env bash

if ! command -v pre-commit > /dev/null; then
    cat <<- EOF
+---------------------------------------------------------+
|    Could not find 'pre-commit' executable in PATH       |
|                                                         |
| If you would like to make use of the pre-commit hooks,  |
| install pre-commit, then run 'cargo make dev-env' again |
+---------------------------------------------------------+
EOF
    exit
else
    pre-commit install > /dev/null
fi
'''

[tasks.dev-env]
dependencies = [
    "install-clippy",
    "install-rustfmt",
    "install-pre-commit-hook",
    "install-cross"
]

[tasks.coverage-llvm-cov]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--lcov", "--output-path", "lcov.info"]
dependencies = ["test"]
