---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1,4"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  ci:
    needs:
      - lint
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make binary
        uses: davidB/rust-cargo-make@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build coverage
        run: cargo make coverage-llvm-cov

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info

  docs:
    name: "Docs"
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2


      - name: Generate docs
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  publish:
    name: "Publish to crates.io"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs:
      - ci
      - docs
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  release:
    name: Release ${{ matrix.target.name }}
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs:
      - ci
      - docs
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: aarch64-unknown-linux-gnu
            binary: ${{ github.event.repository.name }}
          - name: x86_64-unknown-linux-gnu
            binary: ${{ github.event.repository.name }}
          # MacOS support isn't available in cross natively, we'd need to build custom images
          # skip for now
          #- x86_64-apple-darwin
          - name: x86_64-pc-windows-gnu
            binary: ${{ github.event.repository.name }}.exe
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: "${{ matrix.target.name }}"
          override: true
          toolchain: stable

      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

      - name: Build release binary
        run: cross build --release --target ${{ matrix.target.name }}
        env:
          RUSTFLAGS: "-Dwarnings"

      - name: Create asset archive
        run: tar cvzf binary.tar.gz --directory=target/${{ matrix.target.name }}/release ${{ matrix.target.binary }}

      - name: Get current GitHub release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: binary.tar.gz
          asset_name: ${{ github.event.repository.name }}-${{ matrix.target.name }}.tar.gz
          asset_content_type: application/tar+gzip
