name: github

on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4
