# This workflow triggers a new Release if a release PR has just been merged
# If you want to create a new release, use the release-pr workflow instead
name: Trigger GitHub release

on:
  push:
    branches:
      - main

jobs:
  publish-release:
    name: Trigger release
    runs-on: ubuntu-latest
    steps:
      - name: Update and retrieve current release version
        uses: release-drafter/release-drafter@v5
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger release if version matches latest commit message
        if: github.event.head_commit.message == format('Release {0}', steps.drafter.outputs.release_name)
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
