# This workflow triggers a new Release if a release PR has just been merged
# If you want to create a new release, use the release-pr workflow instead
name: Trigger GitHub release

on:
  push:
    branches:
      - main

jobs:
  publish-release:
    name: Push release (or draft)
    runs-on: ubuntu-latest
    steps:
      - name: Update and retrieve current draft release version
        uses: release-drafter/release-drafter@v5
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save desired version string
        run: |
          echo "DESIRED_VER='Release ${{steps.drafter.outputs.release_name }}'" >> $GITHUB_ENV
      - name: Trigger release if version matches latest commit message
        if: startsWith(github.event.head_commit.message, env.DESIRED_VER)
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
